---
title: "Extract MONAN predictions for sites of interest."
author: "Marcos Longo"
date: "2026-02-26"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE,message=FALSE, results='hide', collapse = TRUE)
```

# Introduction

This notebook describes the shell script `03_extract_MONAN.bash`. As of now, we recommend running the script directly as opposed to calling it from RStudio, and use the R Markdown version as a guide for the approach used in the script.


# User-defined script settings.

The first few chunks should contain all the settings to run the script according to the user's needs.

## Path settings

Set the relevant paths:

* `MAIN_PATH`. This sets the location where this script is located. If running locally, it is possible to use generic settings such as `$(cd $(dirname ${0}) && pwd)`, but this will likely fail if submitting a job.
* `OBSER_PATH`. The path where observations were generated.
* `OPER_PATH`. This is the path containing MONAN simulations. 
* `IN_MONAN_PATH`. Path where the subsets of MONAN simulations were generated (see [01_gen_ncdf_intercomp.bash](01_gen_ncdf_intercomp.html)).
* `OUT_MONAN_PATH`. Path to where the extracted site data should be written.

```{bash, label = 'set-paths'}
MAIN_PATH="/path/to/EvalMONANSfc"
OBSER_PATH="${MAIN_PATH}/Observations"
OPER_PATH="/path/to/MONAN_Forecasts/scripts_CD-CT/dataout"
IN_MONAN_PATH="${MAIN_PATH}/ArchiveMASTER"
OUT_MONAN_PATH="${MAIN_PATH}/SiteForecast"
```

## Simulation identification

Here we define two variables:

* `MONAN_PREFIX` is the prefix used for identifying runs. This should be consistent with script [01_gen_ncdf_intercomp.bash](01_gen_ncdf_intercomp.html), and **should not** include the initial time identifier (i.e., `"00Z"` or `"12Z"`).
* `MONAN_SUFFIX` is the suffix used for identifying runs. This should be consistent with script [01_gen_ncdf_intercomp.bash](01_gen_ncdf_intercomp.html).

```{bash, label = 'set-prefix-suffix'}
MONAN_PREFIX="MONAN-1.4.3rc_10km"
MONAN_SUFFIX="SurfaceEval_x5898242L55"
```

## Look-up table position of relevant information

The following variables are the column indices corresponding to the site identity (`SITE_IDENT_POS`), site longitude (`SITE_LON_POS`) and site latitude (`SITE_LAT_POS`) in the site lists.
```{bash, label = 'site-list-position'}
SITE_IDENT_POS=1
SITE_LON_POS=2
SITE_LAT_POS=3
```
## Bounding box settings.

The values here define the edges of the region of interest. Currently, the longitude must be in the -180 through 180 range. In the future, this will be extended to work with the 0-360 range too. 

* `WEST_LON`. This is the westernmost  edge.
* `EAST_LON`. This is the easternmost  edge.
* `SOUTH_LAT`. This is the southernmost edge.
* `NORTH_LAT`. This is the northernmost edge.
```{bash,label='set-bounds'}
WEST_LON=-120   # Westernmost  edge
EAST_LON=-20    # Easternmost  edge
SOUTH_LAT=-60   # Southernmost edge
NORTH_LAT=30    # Northernmost edge
```

## Variable list

Variable `VAR_LIST` should be a bash vector/array containing the list of variables in the input that should be included in the table.

```{bash,label='set-variables'}
VAR_LIST=("surface_pressure" "mslp" "acswdnb" "u10" "v10" "q2" "t2m"
          "pvap2m" "td2m" "rain" "ter")
```

## Required libraries

In this part, you should include commands that will load CDO and NCL. These are necessary for running this script and are machine-specific. If these have been installed with apt-get (Ubuntu), HomeBrew (MacOS) or similar systems, you can comment this part out and run the script directly. To figure out whetehr or not CDO and NCL are readily available, try `which cdo` and `which ncks` on your terminal. If they are available, you should see the full-path location of these executables. Otherwise, if you get nothing back and don't know what to do, maybe check with your IT support team.

```{bash,label='load-cdo-ncl'}
module purge
module load ncl
module load nco
module load cdo
```

This concludes the script configuration section. Changes below this point are needed only if you are developing the script.

# Internal script settings

We create the output path.

```{bash,label='make-path'}
mkdir -pv ${OUT_MONAN_PATH}
```


We then turn the vector of variables into a comma-separated list

```{bash,label='var-list-comma'}
SELVAR_COMMA=$(IFS=","; echo "${VAR_LIST[*]}")
```


We also create a temporary path as we will generate many intermediate files.

```{bash,label='make-temp-path'}
TEMP_PATH="${MAIN_PATH}/DeleteMe"
/bin/rm -fr ${TEMP_PATH}
mkdir -pv ${TEMP_PATH}
```

Look for list of sites. The previous scripts create one sub-directory for each observation type (INMET, METAR, etc.). Likewise, MONAN's subset files create separate sub-directories based on the initial forecast time (00 UTC, 12 UTC), so we looks for files in all sub-directories.

```{bash,label='file-inventory'}
MONAN_BASE=${MONAN_PREFIX}_???_??????????_${MONAN_SUFFIX}.nc
SITE_LIST=$(/bin/ls ${OBSER_PATH}/*/*_SiteInfo.csv      2> /dev/null)
MONAN_LIST=$(/bin/ls ${IN_MONAN_PATH}/*/${MONAN_BASE}   2> /dev/null)
N_SITE_LIST=$(/bin/ls ${OBSER_PATH}/*/*_SiteInfo.csv    2> /dev/null | wc -l)
N_MONAN_LIST=$(/bin/ls ${IN_MONAN_PATH}/*/${MONAN_BASE} 2> /dev/null | wc -l)
```

In case the script fails finding files, stop the run.
```{bash,label='check-inventory'}
if [[ ${N_SITE_LIST} -eq 0 ]] || [[ ${N_MONAN_LIST} -eq 0 ]]
then
   echo "---~---"
   echo "   FATAL ERROR!!!"
   echo "---~---"
   echo ""
   echo "   Failed finding input files needed. Check settings below:"
   echo ""
   echo "   - Path to reference site files:         \"${SITE_PATH}\""
   echo "   - Path to MONAN forecast files:         \"${IN_MONAN_PATH}\""
   echo "   - Prefix for MONAN forecasts:           \"${MONAN_PREFIX}\""
   echo "   - Suffix for MONAN forecasts:           \"${MONAN_SUFFIX}\""
   echo "   - Number of reference site files found: ${N_SITE_LIST}"
   echo "   - Number of MONAN forecast files found: ${N_MONAN_LIST}"
   echo "---~---"
   exit -1   
fi
```


# Data processing

In this chunk we loop through all site lists and initial times for forecasts, and perform the following major tasks.

1. Retrieve all coordinates and site identifiers from the site lists.
2. Run CDO to extract all variables for the site points, creating a temporary NetCDF with unstructured grid with sites.
3. Extract data from the unstructured NetCDF, and create a table.
4. Turn the table file into a space-separated file.
5. Make sure each site is properly identified in the table.

```{bash,label='data-processing-loop'}
for SITE_FILE in ${SITE_LIST}
do
   # Retrieve site list.
   SITE_BASE=$(basename ${SITE_FILE})
   SITE_TYPE=$(basename ${SITE_BASE} .csv | sed s@"_SiteInfo"@""@g)
   SITE_PREFIX=$(echo ${SITE_TYPE} | tr '[:upper:]' '[:lower:]')
   echo " + Processing ${SITE_TYPE} sites listed in \"${SITE_BASE}\":"


   # Extract information from file.
   IDENT_LIST=$(tail -n +2 "${SITE_FILE}" | cut -d',' -f${SITE_IDENT_POS} | tr '\n' ' ')
   LON_LIST=$(tail   -n +2 "${SITE_FILE}" | cut -d',' -f${SITE_LON_POS}   | tr '\n' ' ')
   LAT_LIST=$(tail   -n +2 "${SITE_FILE}" | cut -d',' -f${SITE_LAT_POS}   | tr '\n' ' ')


   # Extract information from file.
   read -r -a IDENT_VEC <<< "${IDENT_LIST}"
   read -r -a LON_VEC   <<< "${LON_LIST}"
   read -r -a LAT_VEC   <<< "${LAT_LIST}"



   # Create file name for site coordinates.
   COORD_FILE="${TEMP_PATH}/${SITE_TYPE}_Coordinates.txt"


   # Tally the site list.
   N_SITES=$(cat ${SITE_FILE} | tail -n +2| wc -l)


   # Create a grid file with all sites.
   if [[ -s ${COORD_FILE} ]]
   then
      /bin/rm -f ${COORD_FILE}
   fi
   touch ${COORD_FILE}

   # Append information for site extraction.
   echo "gridtype = unstructured" >> ${COORD_FILE}
   echo "gridsize = ${N_SITES}"   >> ${COORD_FILE}
   echo "xvals    = ${LON_LIST}"  >> ${COORD_FILE}
   echo ""                        >> ${COORD_FILE}
   echo "yvals    = ${LAT_LIST}"  >> ${COORD_FILE}
   echo ""                        >> ${COORD_FILE}


   # Loop through every MONAN forecast file and extract site list.
   for MONAN_FILE in ${MONAN_LIST}
   do
      # Load forecast information.
      MONAN_BASE=$(basename ${MONAN_FILE} .nc)
      MONAN_ZERO=$( echo ${MONAN_BASE} \
                  | sed s@"${MONAN_PREFIX}_"@""@g )
      MONAN_INIT=${MONAN_ZERO:0:3}
      MONAN_ZERO=$( echo ${MONAN_BASE} \
                  | sed s@"${MONAN_PREFIX}_"@""@g \
                  | sed s@"${MONAN_INIT}_"@""@g   \
                  | sed s@"_${MONAN_SUFFIX}"@""@g )
      MONAN_ZLAB="${MONAN_ZERO:0:4}-${MONAN_ZERO:4:2}-${MONAN_ZERO:6:2}-${MONAN_ZERO:8-2}"
      echo "   - Process forecasts initialised on ${MONAN_ZLAB}."


      # Create temporary NetCDF with extracted sites.
      echo "     ~ Extract site information."
      MONAN_SITE_NC="${TEMP_PATH}/${SITE_TYPE}_SiteData.nc"
      cdo -s -O -L remapnn,"${COORD_FILE}" ${MONAN_FILE} ${MONAN_SITE_NC}



      # Create file with the basic data (site, time, longitude, latitude).
      MONAN_SITE_TXT="${TEMP_PATH}/${SITE_TYPE}_SiteData.txt"


      # Loop through variables, and create one file for each variable.
      for v in ${!VAR_LIST[*]}
      do
         # Pick variable.
         VAR_NOW=${VAR_LIST[v]}
         VAR_FILE_NC="${TEMP_PATH}/${SITE_TYPE}_${VAR_NOW}.nc"
         VAR_FILE_TXT="${TEMP_PATH}/${SITE_TYPE}_${VAR_NOW}.txt"


         # Extract variable
         cdo -s -O -selname,"${VAR_NOW}" ${MONAN_SITE_NC} ${VAR_FILE_NC}


         #   If this is the first variable, first initialise table data with basic
         # information.
         if [[ ! -s ${MONAN_SITE_TXT} ]]
         then
            echo "     ~ Initialise table data."
            cdo -s -O -outputtab,xind,date,time,timestep,lon,lat ${VAR_FILE_NC}            \
               > ${MONAN_SITE_TXT}
            sed -i.bck s@"#"@""@g               ${MONAN_SITE_TXT}
            /bin/rm -f ${MONAN_SITE_TXT}.bck
         fi



         # Extract variable data into a table. 
         cdo -s -O -outputtab,value ${VAR_FILE_NC}   > ${VAR_FILE_TXT}
         sed -i.bck s@"#"@""@g               ${VAR_FILE_TXT}
         sed -i.bck s@"value"@"${VAR_NOW}"@g ${VAR_FILE_TXT}
         /bin/rm -f ${VAR_FILE_TXT}.bck




         # Append variable.
         STEP_FILE=${TEMP_PATH}/${SITE_TYPE}_Step.txt
         echo "     ~ Append variable \"${VAR_NOW}\"."
         paste ${MONAN_SITE_TXT} ${VAR_FILE_TXT} > ${STEP_FILE}
         /bin/mv -f ${STEP_FILE} ${MONAN_SITE_TXT}
      done


      # Replace all tabs with spaces
      echo "     ~ Make sure all tabs become spaces and leading spaces are removed."
      sed -i.bck s@"\t"@" "@g            ${MONAN_SITE_TXT}
      sed -i.bck s@"^[[:space:]]*"@""@g  ${MONAN_SITE_TXT}
      sed -i.bck s@"^xind\ "@"ident "@g  ${MONAN_SITE_TXT}
      /bin/rm -f ${MONAN_SITE_TXT}.bck


      #- Loop through each site and replace index with station name.
      echo "     ~ Replace indices with station identifiers."
      THIS_INDEX=0
      for s in ${!IDENT_VEC[*]}
      do
         # Retrieve information for the current site.
         let THIS_INDEX=${THIS_INDEX}+1
         THIS_IDENT=${IDENT_VEC[s]}
         sed -i.bck s@"^${THIS_INDEX}\ "@"${THIS_IDENT} "@g  ${MONAN_SITE_TXT}
         /bin/rm -f ${MONAN_SITE_TXT}.bck
      done

      # Make sure the path for the initialisation time exists.
      OUT_INIT_PATH=${OUT_MONAN_PATH}/${MONAN_PREFIX}_${MONAN_INIT}
      mkdir -pv ${OUT_INIT_PATH}

      # Save the file to the permanent archive
      echo "     ~ Save file to the permanent archive."
      MONAN_SITE_ARCH="${OUT_INIT_PATH}/${SITE_TYPE}_${MONAN_BASE}.txt"
      /bin/mv ${MONAN_SITE_TXT} ${MONAN_SITE_ARCH}
   done
done
```

# Clean up

Before we quit the script, we delete all temporary files and the temporary directory.

```{bash,label='final-clean-up'}
echo " + Remove the temporary directory."
/bin/rm -fr ${TEMP_PATH}
```
