---
title: "MONAN Evaluator (Surface)"
author: "Marcos Longo"
date: "25-Feb-2026"
---

These documents and scripts can be used to help assess [MONAN](https://github.com/monanadmin/MONAN-Model) simulations that have been post-processed with [scripts_CD-CT](https://github.com/monanadmin/scripts_CD-CT) against station data. The processing has a mix of shell scripts and R scripts.

* [01_gen_ncdf_intercomp.bash](01_gen_ncdf_intercomp.html).  This shell script extracts a sub-domain of MONAN output files to a region of interest. This is useful when running wall-to-wall comparisons for a specific sub-domain.
* [02a_ExtractINMET.Rmd](02a_ExtractINMET.html). This R Markdown takes automatic weather station data from [Brazil's National Institute of Meteorology (INMET)](https://bdmep.inmet.gov.br), organise them into more standard csv files and create a look-up table.
* [02b_ExtractMETAR.Rmd](02b_ExtractMETAR.html). This R Markdown takes airport weather (METAR) data obtained upon request from [MASTER](https://www.master.iag.usp.br), organise them into csv files and create a look-up table.
* [03_ExtractMETAR.Rmd](03_extract_MONAN.bash). This shell scripts extract MONAN forecasts for each site with data available during the assessment period.
* [04_EvalMONAN_SfcStation.Rmd](04_EvalMONAN_SfcStation.html). This R Markdown produces a series of comparisons between the model and the observations, and generates multiple plots to help assess the model.


**Important notes**

1. Make sure to download the directory "RUtils" available on [GitHub](https://github.com/mpaiao/EvalMONANSfc), and set variable `util_path` accordingly for R Markdown scripts that have this variable.
2. In the future, we will try to simplify the workflow to reduce the number of steps. We will also add alternative steps 2 that can handle files pooled and curated by Brazil's National Institute for Space Research (INPE).
3. These scripts require multiple R packages, [Climate Data Operators (CDO)](https://code.mpimet.mpg.de/projects/cdo), [netCDF Operators (NCO)](https://nco.sourceforge.net) and [NCAR Command Language (NCL)](https://www.ncl.ucar.edu/Applications/write_netcdf.shtml).